=== simonbeard/metaface/trunk/FestivalNLP/sml-v01.dtd
<!--
#########################################################################
# Speech Markup Language (SML) DTD, version 1.0.
#
# Usage:
# <!DOCTYPE sml SYSTEM "./sml-v01.dtd">
#
# Author: John Stallo
# Date: 11 September, 2000.
#
#########################################################################
-->

<!ENTITY % LowLevelElements 	"pitch |
				rate |
				emph |
				pause |
				volume |
				sayas |
				pron |
				speaker |
				stat">

<!ENTITY % EmotionElements	"angry |
				happy |
				sad |
				fear |
				neutral">

<!ENTITY % HighLevelElements	"angry |
				happy |
				sad |
				fear |
				neutral |
				embed">

<!ELEMENT sml (p)+>

<!ELEMENT p (%HighLevelElements;)+>

<!ELEMENT speaker (#PCDATA | %LowLevelElements;)*>
<!ATTLIST speaker
	gender (male | female) "male"
	name (en1 | us1) "en1">

<!-- 
#######################################
# HIGH-LEVEL TAGS 
#######################################
-->
<!-- EMOTION TAGS -->
<!ELEMENT angry (#PCDATA | %LowLevelElements;)*>
<!ELEMENT happy (#PCDATA | %LowLevelElements;)*>
<!ELEMENT sad (#PCDATA | %LowLevelElements;)*>
<!ELEMENT fear (#PCDATA | %LowLevelElements;)*>
<!ELEMENT neutral (#PCDATA | %LowLevelElements;)*>

<!-- OTHER HIGH-LEVEL TAGS -->
<!ELEMENT embed EMPTY>
<!ATTLIST embed
	type CDATA #REQUIRED
	src CDATA #IMPLIED
	music_file CDATA #IMPLIED
	lyr_file CDATA #IMPLIED>

<!-- 
#######################################
# LOW-LEVEL TAGS
#######################################
-->
<!ELEMENT pitch (#PCDATA | %LowLevelElements;)*>
<!ATTLIST pitch
      middle CDATA #IMPLIED
      base (low | medium | high) "medium"
      range CDATA #IMPLIED>

<!ELEMENT rate (#PCDATA | %LowLevelElements;)*>
<!ATTLIST rate
      speed CDATA #REQUIRED>

<!ELEMENT stat (#PCDATA | %LowLevelElements;)*>

<!-- SPEAKER DIRECTIVES: Tags that can only encapsulate plain text -->
<!ELEMENT emph (#PCDATA)>
<!ATTLIST emph
      level (weakest | weak | moderate | strong) "moderate"
      affect CDATA #IMPLIED
      target CDATA #IMPLIED>

<!ELEMENT pause EMPTY>
<!ATTLIST pause
      length (short | medium | long) "medium"
	  msec CDATA #IMPLIED
	  smooth (yes | no) "no">

<!ELEMENT volume (#PCDATA)>
<!ATTLIST volume
      level CDATA #REQUIRED>

<!ELEMENT sayas (#PCDATA)>
<!ATTLIST sayas
      mode (literal | date | time | phone | currency) #REQUIRED
      modetype (dmy | mdy) "dmy">

<!ELEMENT pron (#PCDATA)>
<!ATTLIST pron
      sub CDATA #REQUIRED>

=== simonbeard/metaface/trunk/FestivalNLP/input/general.xml
<?xml version="1.0"?>
<!DOCTYPE sml SYSTEM "./sml-v01.dtd">

<sml>
	<p>
	     <neutral><speaker gender="female">Future computers will <emph>invite</emph> us to communicate through 
		a mix of speech, gesture, and gaze.</speaker></neutral>
	</p>
	<p>
	      <neutral>
		      <speaker gender="female">You say lasagna, I say <pron sub="larsarnia">lasagna</pron></speaker>
		  </neutral>
	      <happy>You say tomato, I say <pron sub="toemaytoe">tomato</pron></happy>
	</p>
	<p>
		<happy>
		And now, for the stars of the show: Andrew Marriott, Simon Beard, 
		Bernie <pron sub="Cheeren">Tschirren</pron>, and John Stallo!
		</happy>
	</p>
	<p>
		<neutral><speaker gender="female">I can say currency properly, like $5,010.20.</speaker></neutral>
	</p>
	<p>
	<neutral>I'll now take a breath of helium <pause/> <pitch middle="highest">and will continue to talk until it </pitch> runs out</neutral>
	</p>
</sml>
