=== simonbeard/metaface/trunk/FestivalNLP/sml.dtd
<!-- SML DTD -->

<!-- TEXT DESCRIPTION TAGS -->
<!ELEMENT sml (p)+>
<!ELEMENT p (speaker | angry | happy | sad | fear | neutral)+>
<!ELEMENT speaker (#PCDATA | angry | happy | sad | fear | neutral | pitch | rate | emph | pause | volume | sayas | pron)*>
<!ATTLIST speaker
	gender (male | female) "male"
	name (en1 | us1) "en1">

<!-- EMOTION TAGS  -->
<!ELEMENT angry (#PCDATA | pitch | rate | emph | pause | volume | sayas | pron)*>
<!ELEMENT happy (#PCDATA | pitch | rate | emph | pause | volume | sayas | pron)*>
<!ELEMENT sad (#PCDATA | pitch | rate | emph | pause | volume | sayas | pron)*>
<!ELEMENT fear (#PCDATA | pitch | rate | emph | pause | volume | sayas | pron)*>
<!ELEMENT neutral (#PCDATA | pitch | rate | emph | pause | volume | sayas | pron)*>

<!-- SPEAKER DIRECTIVES: Tags that can encapsulate other tags -->
<!ELEMENT pitch (#PCDATA | rate | emph | pause | volume | sayas | pron)*>
<!ATTLIST pitch
      middle CDATA #IMPLIED
      base (low | medium | high) "medium"
      range CDATA #IMPLIED>

<!ELEMENT rate (#PCDATA | pitch | rate | emph | pause | volume | sayas | pron)*>
<!ATTLIST rate
      speed CDATA #REQUIRED>

<!-- SPEAKER DIRECTIVES: Tags that can only encapsulate plain text -->
<!ELEMENT emph (#PCDATA)>
<!ATTLIST emph
      level (weakest | weak | moderate | strong) "moderate"
      affect CDATA #IMPLIED
      target CDATA #IMPLIED>

<!ELEMENT pause EMPTY>
<!ATTLIST pause
      length (short | medium | long) "medium">

<!ELEMENT volume EMPTY>
<!ATTLIST volume
      level (soft | normal | loud) "normal">

<!ELEMENT sayas (#PCDATA)>
<!ATTLIST sayas
      mode (literal | date | time | phone | currency) #REQUIRED
      modetype (dmy | mdy) "dmy">

<!ELEMENT pron (#PCDATA)>
<!ATTLIST pron
      sub CDATA #REQUIRED>

=== simonbeard/metaface/trunk/FestivalNLP/input/emph.xml
<?xml version="1.0"?>
<!DOCTYPE sml SYSTEM "./sml.dtd">

<sml>
	<p>
	   <neutral>
	      I have told you so many times.
	      I have <emph level="weak" target="ou">told</emph> you <emph target="oo">so</emph> many times.
	      I have <emph level="weak" target="ou">told</emph> you <emph target="oo">so</emph> <emph target="e">many</emph> times.
	   </neutral>
	</p>
</sml>

=== simonbeard/metaface/FestivalNLP/input/testSpeechShort.xml
<?xml version="1.0"?>
<!DOCTYPE sml SYSTEM "./sml.dtd">

<sml>
	<p><neutral>
Hi all, 
	As you have seen, the new time for the lecture for CG is on a
wednesday from 7:30 to 9:30. I am sorry that this is the new time and that
it may cause problems for some of you.
	</neutral></p>

	<p><speaker gender="female"><neutral>
The situation is that I made a mistake in thinking that CG252 was on a monday
night not on the tuesday. Because of family commitments, this time was
extremely difficult for me and as soon as I realised the problem, I
attempted to look for a solution that would affect as few people as
possible. 
	</neutral></speaker></p>

	<p><neutral>
After talking with Mary Simpson, the swap with DB252 seemed ideal
and Raj was happy to help out.  Unfortunately it turned out that there were
some unforseen students who could NOT attend the new DB252 time of 5:30 - 7:30
and so that time was not possible. We then looked for solutions in making
the swap work but after several attempts it was abandoned.
	</neutral></p>

	<p><neutral>
We then looked for the best free 2 hour slot at night.
Initially monday was thought to be ok but that clashes with 2 core units.
The only free slot besides friday night was on the wed 7:30 - 9:30.
Friday night is ok for me but I doubt if you lot would be happy :?)
	</neutral></p>
</sml>
