=== simonbeard/metaface/trunk/javadoc_dev/resources/dmtl.dtd
<!--
#########################################################################
# Dialogue Manager Tool Markup Language (DMTL) DTD, version 4.0.
#
# Usage:
# <!DOCTYPE dialogue SYSTEM "http://www.vhml.org/DTD/dmtl.dtd">       
#
# Author: 
# Date: 17 October 2001
#
#########################################################################
-->


<!ELEMENT dialogue (macros?, defaulttopic?, topic*)>

<!ELEMENT macros (macro)*>

<!ELEMENT macro (stimulus)*>
<!ATTLIST macro 
        name CDATA #REQUIRED>

		<!--
		# This is used to specify a default answer that triggers if
                # there is no other answers matching the stimulus
		-->
<!ELEMENT defaulttopic (state)+>


<!ELEMENT topic (subtopic)*>
<!ATTLIST topic
	name CDATA #REQUIRED>


<!ELEMENT subtopic (state | subtopic)*>
<!ATTLIST subtopic
	name CDATA #REQUIRED
        keywords CDATA #IMPLIED
        evaluate CDATA #IMPLIED>


		<!--
		# It has a type to cater for the different types of nodes 
                # that may need to be specified (for example, some nodes may 
                # be "active" - that is, the Dialogue Manager which uses this 
                # file may use an "active" node to ask the user questions or 
                # make observations, not just respond to stimulus. 
    		# linked - the stimulus is matched only from "nextstates" 
    		# active - pro-active interaction with the user. 
    		# entry - these stimuli are used for initial input from user 
    		# switch - the start of a chained stimulus-response set of 
                # states to cater for learned
             	# behaviour in the user. 
		-->
<!ELEMENT state (stimulus*,
                 response*,
                 (prestate*,nextstate*,signal*)*, 
                 evaluate?, 
                 other?) >
<!ATTLIST state
	name CDATA #REQUIRED
	type (linked | active | entry | visitswitch ) "entry">


		<!--
		# The stimulus is typically a question or a response to a 
                # question or could be input from a
		# facial recognition system - a shrug, a nod, etc. 
		# Case is important in the input. 
		-->
<!ELEMENT stimulus (#PCDATA)>    
<!ATTLIST stimulus
	type (text | visual | audio | haptic) "text">


		<!--
		# The response is typically a response but marked up in vhml. 
                # The response could be text,
		# XHTML text, text plus EML, etc. The response could also be 
                # a question for pro-active
		# dialogues.
		# The vhml does not have the vhml root tag. 
		#
		#The DTD for response is: 
		<!ELEMENT response (vhml)>    
		-->
                <!-- 
		# The response weight is a floating point number between 0.0 
                # and 1.0 with 0.0 meaning no
		# confidence in this response and 1.0 meaning total confidence 
                # in the response.
		# A value of 0.7 could be the typical value for most responses 
                # which match. This gives the
		# ability to have other responses match but at a higher priority 
                # because the response is seen
		# as being more important in this situtation
		# The default value for a responseweight is 0.7.
		# The Dialogue Manager may ignore this value. 
		-->
<!ELEMENT response (#PCDATA)>    
<!ATTLIST response
	weight CDATA "0.7"
        statereference CDATA #IMPLIED>


		<!--
		# A signal tag enables the match to generate a signal or a 
                # notification to the Dialogue
		# Manager which it may choose to ignore. An example of the use of this 
                # is if the match has
		# determined that the user wants to finish the dialogue and hence 
                # the DM should know to finish. 
                # The value of the signals should be one of a set of descripted values
                # instead of just CDATA, but these values are not yet decided which to be.
		# 
		# The DTD for signal is: 
		-->
<!ELEMENT signal EMPTY>    
<!ATTLIST signal
        name CDATA #REQUIRED>


		<!--
		# The prestate tag specifies a set of states which must match 
                # for this state to match the
		# stimulus. This allows for catering for a specific "yes" answer 
                # but only to the prestate question. 
		# 
		# The DTD for prestate is: 
		-->
<!ELEMENT prestate EMPTY>    
<!ATTLIST prestate
	name CDATA #REQUIRED>


		<!--
		# The nextstate tag specifies a set of states to test for followup 
                # stimulus input. These states
		# would be checked first (perhaps with some increase in the 
                # responseweighting?) before all
		# other states. This allows for catering for a specific "yes" answer 
                # to this response. 
		# 
		# The DTD for nextstate is: 
		-->
<!ELEMENT nextstate EMPTY>    
<!ATTLIST nextstate
	name CDATA #REQUIRED>

		<!--
		# The evaluate tag specifies different application specific test
                # that has to be made. If the contained data begins with // it 
                # means that it is a comment.
		# 
		# The DTD for evaluate is: 
		-->
<!ELEMENT evaluate (#PCDATA)>    


		<!--
		# The other tag gives the oppurtunity to specify other application
                # specific information.
		# 
		# The DTD for other is: 
		-->
<!ELEMENT other (#PCDATA)>

=== simonbeard/metaface/trunk/javadoc/resources/dmtl_example.xml
<?xml version="1.0"?>
<!DOCTYPE dialogue SYSTEM "./dmtl.dtd">
<dialogue>
    <macros>
	<!-- Technical Words: Talking Heads -->
        <macro name="THS">
            <stimulus type="text">
                th
            </stimulus>
            <stimulus type="text">
                ths
            </stimulus>
            <stimulus type="text">
                talking head
            </stimulus>
            <stimulus type="text">
                talking heads
            </stimulus>
        </macro>
        <macro name="NATURAL_LANGUAGE">
            <stimulus type="text">
                natural language
            </stimulus>
        </macro>
        <macro name="KEY_FRAME">
            <stimulus type="text">
                key-frame
            </stimulus>
            <stimulus type="text">
                key frame 
            </stimulus>
            <stimulus type="text">
                keyframe 
            </stimulus>
            <stimulus type="text">
                key-frame algorithm
            </stimulus>
            <stimulus type="text">
                key frame algorithm
            </stimulus>
            <stimulus type="text">
                keyframe algorithm
            </stimulus>
            <stimulus type="text">
		key-frame animation
            </stimulus>
            <stimulus type="text">
                key frame animation
            </stimulus>
            <stimulus type="text">
                keyframe animation
            </stimulus>
        </macro>
        <macro name="PARAMETER_BASED">
            <stimulus type="text">
                parameter-based
            </stimulus>
            <stimulus type="text">
                parameter based
            </stimulus>
            <stimulus type="text">
                parameterbased
            </stimulus>
            <stimulus type="text">
                parameter-based algorithm
            </stimulus>
            <stimulus type="text">
                parameter based algorithm
            </stimulus>
            <stimulus type="text">
                parameterbased algorithm
            </stimulus>
            <stimulus type="text">
                parameter-based animation
            </stimulus>
            <stimulus type="text">
                parameter based animation
            </stimulus>
            <stimulus type="text">
                parameterbased animation
            </stimulus>
        </macro>
        <macro name="DOWNLOAD_TO_CACHE">
            <stimulus type="text">
                download-to-cache
            </stimulus>
            <stimulus type="text">
                download to cache
            </stimulus>
            <stimulus type="text">
                download-to-cache transmission
            </stimulus>
            <stimulus type="text">
                download to cache transmission
            </stimulus>
            <stimulus type="text">
                download-to-cache data transmission
            </stimulus>
            <stimulus type="text">
                download to cache data transmission
            </stimulus>
        </macro>
        <macro name="PROGRESSIVE_DOWNLOAD">
            <stimulus type="text">
                progressive download
            </stimulus>
            <stimulus type="text">
                progressive download transmission
            </stimulus>
            <stimulus type="text">
                progressive download data transmission
            </stimulus>
            <stimulus type="text">
                progressive
            </stimulus>
            <stimulus type="text">
                progressive transmission
            </stimulus>
            <stimulus type="text">
                progressive data
            </stimulus>
        </macro>
        <macro name="REAL_TIME">
            <stimulus type="text">
                real-time
            </stimulus>
            <stimulus type="text">
                real time
            </stimulus>
            <stimulus type="text">
                realtime
            </stimulus>
            <stimulus type="text">
                real-time streaming
            </stimulus>
            <stimulus type="text">
                real time streaming
            </stimulus>
            <stimulus type="text">
                realtime streaming
            </stimulus>
            <stimulus type="text">
                real-time transmission
            </stimulus>
            <stimulus type="text">
                real time transmission
            </stimulus>
            <stimulus type="text">
                realtime transmission 
            </stimulus>
            <stimulus type="text">
                real-time data transmission
            </stimulus>
            <stimulus type="text">
                real time data transmission
            </stimulus>
            <stimulus type="text">
                realtime data transmission
            </stimulus>
        </macro>
        <macro name="3D">
            <stimulus type="text">
                3d
            </stimulus>
            <stimulus type="text">
                3-d
            </stimulus>
            <stimulus type="text">
                three-d
            </stimulus>
            <stimulus type="text">
                three d
            </stimulus>
            <stimulus type="text">
                3 dimensional
            </stimulus>
            <stimulus type="text">
                3-dimensional
            </stimulus>
            <stimulus type="text">
                three dimensional
            </stimulus>
            <stimulus type="text">
                three-dimensional
            </stimulus>
            <stimulus type="text">
                three dimensions
            </stimulus>
        </macro>
        <macro name="2D">
            <stimulus type="text">
                2d
            </stimulus>
            <stimulus type="text">
                2-d
            </stimulus>
            <stimulus type="text">
                two-d
            </stimulus>
            <stimulus type="text">
                two d
            </stimulus>
            <stimulus type="text">
                2 dimensional
            </stimulus>
            <stimulus type="text">
                2-dimensional
            </stimulus>
            <stimulus type="text">
                two dimensional
            </stimulus>
            <stimulus type="text">
                two-dimensional
            </stimulus>
            <stimulus type="text">
                two dimensions
            </stimulus>
        </macro>
	<macro name="IBR">
            <stimulus type="text">
                ibr
            </stimulus>
            <stimulus type="text">
                image-based rendering
            </stimulus>
            <stimulus type="text">
                image based rendering
            </stimulus>
            <stimulus type="text">
                imagebased rendering
            </stimulus>
        </macro>

	<!-- Technical Words: MPEG-4 -->
        <macro name="_MPEG">
            <stimulus type="text">
                moving picture experts group
            </stimulus>
            <stimulus type="text">
                moving pictures expert group
            </stimulus>
            <stimulus type="text">
                moving pictures experts group
            </stimulus>
            <stimulus type="text">
                moving picture expert group
            </stimulus>
        </macro>
        <macro name="MPEG4">
            <stimulus type="text">
                mpeg-4
            </stimulus>
            <stimulus type="text">
                mpeg4
            </stimulus>
            <stimulus type="text">
                mpeg 4
            </stimulus>
            <stimulus type="text">
                _MPEG 4
            </stimulus>
            <stimulus type="text">
                _MPEG
            </stimulus>
        </macro>
        <macro name="PHONEME">
            <stimulus type="text">
                phoneme
            </stimulus>
            <stimulus type="text">
                phonemes
            </stimulus>
        </macro>
        <macro name="VISEME">
            <stimulus type="text">
                viseme
            </stimulus>
            <stimulus type="text">
                visemes
            </stimulus>
        </macro>
        <macro name="PROSODY">
            <stimulus type="text">
                prosody
            </stimulus>
            <stimulus type="text">
                range
            </stimulus>
            <stimulus type="text">
                pitch
            </stimulus>
            <stimulus type="text">
                speed
            </stimulus>
            <stimulus type="text">
                rate
            </stimulus>
        </macro>	
        <macro name="VISUAL_STANDARD">
            <stimulus type="text">
                visual standard
            </stimulus>
            <stimulus type="text">
                visual-standard
            </stimulus>
            <stimulus type="text">
                visual std
            </stimulus>
        </macro>
        <macro name="_FACIAL">
            <stimulus type="text">
                facial
            </stimulus>
            <stimulus type="text">
                face
            </stimulus>
        </macro>
        <macro name="FACIAL_ANIMATION">
            <stimulus type="text">
                _FACIAL animation
            </stimulus>
        </macro>
        <macro name="NEUTRAL_FACE">
            <stimulus type="text">
                neutral face
            </stimulus>
